export const supplierForm = [
  {
    key: "name",
    value: "name",
    label: "Supplier name",
    placeholder: "Enter supplier name",
    type: "default",
    required: true,
    message: "Enter supplier name",
    default_value: "",
  },
  {
    key: "email",
    value: "email",
    label: "Supplier Email",
    placeholder: "Enter supplier email",
    type: "default",
    default_value: "",
  },
  {
    key: "active",
    value: "active",
    label: "Supplier active",
    placeholder: "Enter supplier active",
    type: "number",
    message: "Enter supplier name",
    default_value: "",
  },
  {
    key: "product",
    value: "product",
    label: "Supplier product",
    placeholder: "Enter supplier product",
    type: "default",
    message: "Enter supplier product",
    default_value: "",
  },
  {
    key: "categories",
    value: "categories",
    label: "Supplier categories",
    placeholder: "Enter supplier categories",
    type: "select",
    message: "",
    default_value: [],
    lookup_items: [],
  },
  {
    key: "price",
    value: "price",
    label: "Supplier price",
    placeholder: "Enter supplier price",
    type: "number",
    message: "",
    default_value: "",
  },

  {
    key: "contact",
    value: "contact",
    label: "Supplier contact",
    placeholder: "Enter supplier contact",
    type: "number",
    message: "",
    default_value: "",
  },

  {
    key: "type",
    value: "isTaking",
    label: "Taking",
    placeholder: "",
    type: "checkbox",
    message: "",
    default_value: null,
  },
];
